services:
    napcat:
        image: mlikiowa/napcat-docker:v4.17.25
        container_name: ${CONTAINER_NAME}
        restart: always
        network_mode: "host"
        mac_address: "${MAC_ADDRESS}"
        privileged: true
        environment:
            - "TZ=Asia/Shanghai"
            - "NAPCAT_UID=${NAPCAT_UID}"
            - "NAPCAT_GID=${NAPCAT_GID}"
        volumes:
            - "${QQ_PATH}:/app/.config/QQ"
            - "${CONFIG_PATH}:/app/napcat/config"
            - "${CONFIG_PATH}/plugins:/app/napcat/plugins"
            - "${CHROME_PATH}:/app/.cache/puppeteer/chrome"
            - "${LOG_PATH}:/app/napcat/logs"
            - "${ADDITIONAL_PATH1:-/dev/null}:${ADDITIONAL_PATH1:-/app/zero}"
            - "${ADDITIONAL_PATH2:-/dev/null}:${ADDITIONAL_PATH2:-/app/one}"
            - "${ADDITIONAL_PATH3:-/dev/null}:${ADDITIONAL_PATH3:-/app/two}"
        labels:
            createdBy: "Apps"
